/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package footwear_factory;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author arvin
 */
public class userMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form userMainScreen
     */
    public userMainScreen() {
        initComponents();
        jLabel6.setText("-");
        jLabel7.setText("$");
        

        
        DefaultTableModel shoeTable = (DefaultTableModel) shoesTable.getModel(); 
        shoeTable.setRowCount(0);
        try {
                        Class.forName("oracle.jdbc.driver.OracleDriver");
              } catch (ClassNotFoundException e) {
                        e.printStackTrace();
                        return;
                }
                Connection connection = null;
                try {
                         connection = DriverManager.getConnection("jdbc:oracle:thin:@acaddbprod.uta.edu:1523/pcse1p.data.uta.edu", "axr0501", "Arvisitaram5");
                } catch (SQLException e) {
                        System.out.println("Connection Failed!");
                        e.printStackTrace();
                        return;
                }
        try {
            Statement stmt = connection.createStatement();
               ResultSet rs = stmt.executeQuery("select * from Fall22_S001_5_shoes");
               Integer i=1;
               while (rs.next()) {
                  String[] row = {i.toString(), rs.getString(1), rs.getString(5), rs.getString(4)};
                   shoeTable.addRow(row);
                   i++;
               }
               rs.close();
               stmt.close();
            connection.close();
        }
        catch (SQLException e) {
                        System.out.println("error in accessing the relation");
                        e.printStackTrace();
                        return;
         } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        shoesTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        shoePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        hidCB = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        shoesTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1053, 657));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME USER!");

        jButton1.setText("Back");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        shoesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "SKU", "Model Name", "Retail Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        shoesTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(shoesTable);
        shoesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (shoesTable.getColumnModel().getColumnCount() > 0) {
            shoesTable.getColumnModel().getColumn(0).setPreferredWidth(45);
            shoesTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            shoesTable.getColumnModel().getColumn(2).setPreferredWidth(25);
            shoesTable.getColumnModel().getColumn(2).setHeaderValue("Quantity");
            shoesTable.getColumnModel().getColumn(3).setPreferredWidth(45);
        }

        jButton2.setText("View Selected Shoe");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        shoePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SHOE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Size:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Stock Availability:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Selling Price:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("jLabel7");

        jButton3.setText("BUY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        hidCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Size" }));
        hidCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shoePanelLayout = new javax.swing.GroupLayout(shoePanel);
        shoePanel.setLayout(shoePanelLayout);
        shoePanelLayout.setHorizontalGroup(
            shoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(shoePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(shoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(shoePanelLayout.createSequentialGroup()
                        .addGroup(shoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(shoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hidCB, 0, 102, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(213, 213, 213))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shoePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        shoePanelLayout.setVerticalGroup(
            shoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(shoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hidCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(shoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(shoePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setText("Orders");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        shoesTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Model Name", "Size", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(shoesTable1);
        shoesTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (shoesTable1.getColumnModel().getColumnCount() > 0) {
            shoesTable1.getColumnModel().getColumn(0).setPreferredWidth(45);
            shoesTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
            shoesTable1.getColumnModel().getColumn(2).setPreferredWidth(25);
            shoesTable1.getColumnModel().getColumn(3).setPreferredWidth(45);
        }

        jButton5.setText("SELL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButton2)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shoePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(shoePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainScreen mS = new mainScreen();
        mS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    String selectedSku;
    Float selectedSize;
    Integer selectedQty;
    Float selectedPrice;
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int row = shoesTable.getSelectedRow();
         String sku = (String) shoesTable.getModel().getValueAt(row, 1);
         selectedSku = sku;
         try {
                        Class.forName("oracle.jdbc.driver.OracleDriver");
              } catch (ClassNotFoundException e) {
                        e.printStackTrace();
                        return;
                }
                Connection connection = null;
                try {
                         connection = DriverManager.getConnection("jdbc:oracle:thin:@acaddbprod.uta.edu:1523/pcse1p.data.uta.edu", "axr0501", "Arvisitaram5");
                } catch (SQLException e) {
                        System.out.println("Connection Failed!");
                        e.printStackTrace();
                        return;
                }
        try {
            Statement stmt = connection.createStatement();
               ResultSet rs = stmt.executeQuery("select s.footsize, s.quantity, l.listingprice from Fall22_S001_5_listing l, Fall22_S001_5_stockavailability s where l.sku=s.stocksku and l.sku = '" + sku + "' ");
               rs.next();
               String qty = rs.getString(2);
               selectedQty = Integer.parseInt(qty);
               String size = rs.getString(1);
               String lp = rs.getString(3);
               selectedPrice = Float.parseFloat(lp);
               jLabel6.setText(qty);
                 jLabel7.setText(lp);
                hidCB.addItem(size);
               rs.close();
               stmt.close();
            connection.close();
        }
        catch (SQLException e) {
                        System.out.println("error in accessing the relation");
                        e.printStackTrace();
                        return;
         } 
    }//GEN-LAST:event_jButton2ActionPerformed
    Integer lastOrderID;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                            Footwear_Factory globalInstance = Footwear_Factory.getInstance();

        try {
                        Class.forName("oracle.jdbc.driver.OracleDriver");
              } catch (ClassNotFoundException e) {
                        e.printStackTrace();
                        return;
                }
                Connection connection = null;
                try {
                         connection = DriverManager.getConnection("jdbc:oracle:thin:@acaddbprod.uta.edu:1523/pcse1p.data.uta.edu", "axr0501", "Arvisitaram5");
                } catch (SQLException e) {
                        System.out.println("Connection Failed!");
                        e.printStackTrace();
                        return;
                }
        try {
            Statement stmt = connection.createStatement();
            ResultSet rs0 = stmt.executeQuery("select orderid from fall22_s001_5_orders where orderid = ( select max(orderid) from fall22_s001_5_orders )");
               rs0.next();
               lastOrderID = rs0.getInt(1) + 1;
               rs0.close();
            
            
               ResultSet rs = stmt.executeQuery("update Fall22_S001_5_stockavailability set quantity="+ (selectedQty-1)+" where stocksku='"+selectedSku+"' and footsize="+selectedSize+"");
               rs.next();
               rs.close();
            
                ResultSet rs2 = stmt.executeQuery("Insert into fall22_s001_5_purchasehistory Values('"+selectedSku+"', "+ (globalInstance.getCurrentUserID())+", to_date('2022-12-06','YYYY-MM-DD'), 1)");
            rs2.next();
               rs2.close();
               
               ResultSet rs3 = stmt.executeQuery("Insert into fall22_s001_5_orders Values("+lastOrderID+", 1,"+selectedPrice+" , "+selectedSize+", '"+selectedSku+"')");
            rs3.next();
               rs3.close();
               
               ResultSet rs4 = stmt.executeQuery("Insert into Fall22_S001_5_orderplaced Values("+(globalInstance.getCurrentUserID())+", "+lastOrderID+")");
            rs4.next();
               rs4.close();
               
               stmt.close();
            connection.close();
            JOptionPane.showMessageDialog(null,"SHOE PURCHASED!");
            jLabel6.setText("-");
                 jLabel7.setText("$");
                 hidCB.setSelectedIndex(0);
        }
        catch (SQLException e) {
                        System.out.println("error in accessing the relation");
                        e.printStackTrace();
                        return;
         }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    private void hidCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidCBActionPerformed
//        hid = hidCB.getSelectedItem().toString().substring(0, 3);
        selectedSize = Float.parseFloat(hidCB.getSelectedItem().toString());
    }//GEN-LAST:event_hidCBActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         Footwear_Factory globalInstance = Footwear_Factory.getInstance();
        DefaultTableModel rollTable = (DefaultTableModel) shoesTable1.getModel(); 

        rollTable.setRowCount(0);
        try {
                        Class.forName("oracle.jdbc.driver.OracleDriver");
              } catch (ClassNotFoundException e) {
                        e.printStackTrace();
                        return;
                }
                Connection connection = null;
                try {
                         connection = DriverManager.getConnection("jdbc:oracle:thin:@acaddbprod.uta.edu:1523/pcse1p.data.uta.edu", "axr0501", "Arvisitaram5");
                } catch (SQLException e) {
                        System.out.println("Connection Failed!");
                        e.printStackTrace();
                        return;
                }
        try {
            Integer id=1;
            
            Statement stmt = connection.createStatement();
            ResultSet rs0 = stmt.executeQuery("Select o.orderid, s.modelname, o.footsize, o.quantity, o.price  from Fall22_S001_5_orders o, Fall22_S001_5_shoes s where s.sku = o.sku and o.orderid in (Select orderid from Fall22_S001_5_orderplaced where buyerid = "+globalInstance.getCurrentUserID()+")");
            if (rs0.next() == true) {
                                  String[] row = {rs0.getString(1), rs0.getString(2), rs0.getString(3), rs0.getString(4)};
                   rollTable.addRow(row);
                   id++;
                while(rs0.next()) {
                                 String[] row1 = {rs0.getString(1), rs0.getString(2), rs0.getString(3), rs0.getString(4)};
                   rollTable.addRow(row1);
                   id++;
               }
            } else {
                            JOptionPane.showMessageDialog(null,"No stock found!");
            }
            
               rs0.close();
               
               stmt.close();
            connection.close();
        }
        catch (SQLException e) {
                        System.out.println("error in accessing the relation");
                        e.printStackTrace();
                        return;
         }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
                userSellScreen mS = new userSellScreen();
        mS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> hidCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel shoePanel;
    private javax.swing.JTable shoesTable;
    private javax.swing.JTable shoesTable1;
    // End of variables declaration//GEN-END:variables
}
